### ISSUE TITLE
Can't attach a controller without an error middleware

### ISSUE THREAD

**Issue by markkelsall** [serhiisol/node-decorators#165] opened 2023-07-26 14:33 UTC
hi,

Not sure if this is because of the revert you've done, but I can't use an @Controller anymore unless there is an error middleware.

Example controller:
```
@Controller("/")
export class UsersController {
	@Get("/users/:id")
	getData(res, @Params("id") id: string) {
		res.status(200).send({
			id,
			message: "hello"
		});
	}
}
```

Attaching controllers:
`attachControllers(app, [UsersController]);`

The error I get is:
`MissingProviderError: Missing provider ERROR_MIDDLEWARE`
Coming from node_modules/@decorators/di/src/container.ts:43:13)

If I add an error middleware, like so:
```
const serverErrorMiddleware = (error: Error, _: Request, response: Response): any => {
	logger.debug("caught this error", error.message);
	response.status(200).json({ message: "error" });
};

Container.provide([{ provide: ERROR_MIDDLEWARE, useValue: serverErrorMiddleware }]);
```

Then I always get the error response. I never get the response from the controller function.

Secondly, if I put anything other than "/" as the path in @Controller, it doesn't work. 

Like I said, all of this used to work before the changes.
Thanks

**Comment by serhiisol** [comment] 2023-07-26 15:07
Hi @markkelsall, have you tried latest version of the packages? I just checked [example](https://github.com/serhiisol/node-decorators/blob/master/express/example/index.ts) app and it seem to be working correctly without `ERROR_MIDDLEWARE` and with controller urls.

**Comment by markkelsall** [comment] 2023-07-26 15:23
hey, how are you running the example app? I've just updated in my test repo and it's still not working

**Comment by serhiisol** [comment] 2023-07-26 15:26
Ah yes, probably you wound need to change package.json to install `@decorators/di` `^2.0.0` instead of a local version.

**Comment by markkelsall** [comment] 2023-08-15 08:37
Apologies for the delayed response. Unfortunately when I clone the whole repo, npm install in the express folder and open the example index.ts, (without making any changes) it says:
Cannot find module '@decorators/di' or its corresponding type declarations.

When I try to use run and debug I get the following:
/usr/local/bin/node ./express/example/index.ts
(node:2642) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
warning.js:43
Process exited with code 1
Uncaught SyntaxError /Users/kelsallm/workspace/node-decorators/express/example/index.ts:3
import * as express from 'express';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (<node_internals>/internal/modules/cjs/loader.js:979:16)
    at Module._compile (<node_internals>/internal/modules/cjs/loader.js:1027:27)
    at Module._extensions..js (<node_internals>/internal/modules/cjs/loader.js:1092:10)
    at Module.load (<node_internals>/internal/modules/cjs/loader.js:928:32)
    at Module._load (<node_internals>/internal/modules/cjs/loader.js:769:14)
    at executeUserEntryPoint (<node_internals>/internal/modules/run_main.js:72:12)
    at <anonymous> (<node_internals>/internal/main/run_main_module.js:17:47)

**Comment by serhiisol** [comment] 2023-08-15 09:46
did you run ts-node or just a plain node? Cause that error can happen cause of either missing experimental flag or not compiled ts.

**Comment by markkelsall** [comment] 2023-08-15 14:48
I just tried using vscode run and debug, which is what I thought you meant by vs code launch script

**Comment by serhiisol** [comment] 2023-08-15 14:56
Yes What's your npm and nodejs, os versions?

**Comment by markkelsall** [comment] 2023-08-15 14:58
npm - 9.2.0
node - 14..18.2
os - macOS ventura 13.4

**Comment by serhiisol** [comment] 2023-08-15 15:04
Well, from what I can see, ts file cannot be executed with plain nodejs:
```
/usr/local/bin/node ./express/example/index.ts
```
. you need repl such as ts-node.

In launch.json file of express folder I've used ts-node

**Comment by markkelsall** [comment] 2023-08-18 15:40
are you opening just the express folder in vs code and trying to run it from there? or are you opening the whole node-decorators repo and trying from there?
when opening just the express folder, even after I npm install, I still get the "Cannot find module '@decorators/di' or its corresponding type declarations." error in vscode

**Comment by serhiisol** [comment] 2023-08-19 18:12
Basically I have a workspace in vscode where I've added folders. Then I have installed node modules in every folder and then I use launch script in the express folder to start the app.

**Comment by markkelsall** [comment] 2023-08-21 07:59
OK I've got it working finally!!

I had to `cd di && npm i && npm run build` & then `cd express && npm i` which then resolved the deps issue. I'm going to re-check my independent example, but the fact that I had to npm i `di` in the workspace even though the reference is to the npm.com and not a relative path is very confusing.

To run it however, when the whole workspace is open, vscode couldn't pick up the config in launch.json and so there tried to use node, not ts-node. 
I installed a vs-code extension called CodeRun for ts-node to be able to execute it from the file - https://marketplace.visualstudio.com/items?itemName=HaikelFazzani.code-run

**Comment by serhiisol** [comment] 2023-08-21 16:42
Well, I don't use root folder of the repo, I use folders as project in my local `node-decorators` workspace in vscode. In this case, vscode sees properly all the .launch files and I can run everything locally. The reason for `di` to be relative path is that I can install hotfixes if necessary and see if it's working or not.

**Comment by markkelsall** [comment] 2023-08-25 14:35
while this isn't related to the topic of the opening issue, I'm now running into babel issues in my code. Have you had any issues where people have it set up with webpack and babel?

**Comment by serhiisol** [comment] 2023-08-25 15:22
Not that I know of. Express package was not migrated, just fixes. Could you try to downgrade it to see which version caused the issue?

**Comment by serhiisol** [comment] 2023-08-26 11:06
Closing issue, I can't reproduce the problem. If you can provide me a repo where I can reproduce it I'll be able to help. 

here's the example I've used. As you can see I've disabled ERROR_MIDDLEWARE to reproduce the issue.

Hit `npm I && npm start`

```ts
import * as express from 'express';
import { Injectable } from '@decorators/di';
import { Container, attachControllers, Controller, ERROR_MIDDLEWARE, ErrorMiddleware, Get, Middleware } from '@decorators/express';

const app: express.Express = express();

class NotFoundError extends Error { }
class InternalServerError extends Error { }

@Injectable()
class DataProvider {
  data() {
    return { hello: 'world' };
  }
}

@Injectable()
class RequestMiddleware implements Middleware {
  constructor(private dataProvider: DataProvider) { }

  use(_request: express.Request, _response: express.Response, next: express.NextFunction) {
    console.log('RequestMiddleware', this.dataProvider.data());

    next();
  }
}

@Controller('/', [RequestMiddleware])
class IndexController {
  @Get('/')
  index() {
    return 'Hello World';
  }

  @Get('/not-found-error')
  notFoundError() {
    throw new NotFoundError();
  }

  @Get('/internal-server-error')
  internalServerError() {
    throw new InternalServerError();
  }
}

@Injectable()
class ServerErrorMiddleware implements ErrorMiddleware {

  constructor(private dataProvider: DataProvider) { }

  use(error: Error, _request: express.Request, response: express.Response, next: express.NextFunction) {
    console.log(this.dataProvider.data());

    if (error instanceof NotFoundError) {
      return response.send('Not Found Error');
    }

    if (error instanceof InternalServerError) {
      return response.send('Internal Server Error');
    }

    next(error);
  }
}

export async function start() {
  Container.provide([
    { provide: DataProvider, useClass: DataProvider },
    // { provide: ERROR_MIDDLEWARE, useClass: ServerErrorMiddleware },
  ]);

  await attachControllers(app, [IndexController]);

  app.listen(3000, () => {
    console.info('Server is running on port 3000');
  });
}

start().catch(console.error);
```
```json
{
  "dependencies": {
    "@decorators/di": "^3.1.0",
    "@decorators/express": "^3.0.0",
    "@types/express": "^4.17.17",
    "express": "^4.18.2",
    "reflect-metadata": "^0.1.13",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
  "description": "node decorators - decorators for express library",
  "keywords": [
    "nodejs",
    "express",
    "node decorators",
    "typescript"
  ],
  "license": "MIT",
  "main": "lib/index.js",
  "name": "@decorators/express-example",
  "scripts": {
    "start": "ts-node index.ts"
  },
  "version": "3.1.0"
}
```
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "inlineSourceMap": true,
    "inlineSources": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    // "noImplicitAny": false,
    // "noUnusedLocals": true,
    // "noUnusedParameters": true,
    "outDir": "lib",
    "pretty": true,
    "rootDir": ".",
    "target": "ES2017",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "include": [
    "./index.ts"
  ]
}
```

**Closed by serhiisol** 2023-08-26 11:06 UTC
